---
version: "2.1"
networks:
  g-flix:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - ~/g-flix/plex:/config
      - /mnt/media/tv:/tv
      - /mnt/media/movies:/movies
    networks:
      g-flix:
        ipv4_address: 172.20.0.10
    ports:
      - 32400:32400
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
      - TRANSMISSION_WEB_HOME=/combustion-release/ # try: /flood-for-transmission/
      # - USER=username #optional
      # - PASS=password #optional
    volumes:
      - ~/g-flix/transmission:/config
      - /mnt/media/downloads:/downloads
      # - /mnt/media/downloads:/watch # verify what this does
    networks:
      g-flix:
        ipv4_address: 172.20.0.11
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ~/g-flix/jackett:/config
      - /mnt/media/downloads/completed:/downloads
    networks:
      g-flix:
        ipv4_address: 172.20.0.12
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - ~/g-flix/sonarr:/config
      - /mnt/media/tv:/tv
      - /mnt/media/downloads/completed:/downloads
    networks:
      g-flix:
        ipv4_address: 172.20.0.13
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - ~/g-flix/radarr:/config
      - /mnt/media/tv:/tv
      - /mnt/media/downloads/completed:/downloads
    networks:
      g-flix:
        ipv4_address: 172.20.0.14
    ports:
      - 7878:7878
    restart: unless-stopped
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
      - BASE_URL=/ombi #optional
    volumes:
      - ~/g-flix/ombi:/config
    networks:
      g-flix:
        ipv4_address: 172.20.0.15
    ports:
      - 3579:3579
    restart: unless-stopped